FROM vllm/vllm-openai:latest

# Установка недостающих пакетов
RUN pip install verovio

# Создание рабочей директории
WORKDIR /app

# Копирование скриптов запуска
COPY start_server.sh /app/start_server.sh
RUN chmod +x /app/start_server.sh

ENTRYPOINT ["/app/start_server.sh"]
